version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - es-net
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    container_name: kibana
    ports:
        - "5601:5601"
    environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    links:
        - elasticsearch
    depends_on:
        - elasticsearch
    networks:
        - es-net

networks:
  es-net:
    driver: bridge
