version: "3.4"

services:
  mysql:
    image: mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mysql
networks:
  mysql:
    driver: bridge
